//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceName { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
