//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDetail
    {
        public int OrdersDetailID { get; set; }
        public int OrdersID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> DemandQuantily { get; set; }
        public Nullable<decimal> ActualQuantily { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }

    public enum UnitS
    {
        Bottle,
        Can
    }
}
