// <auto-generated />
namespace Management_Distributor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropSomeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropSomeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081338121_DropSomeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
